name: Hello World Workflow

on:
  workflow_dispatch:
    inputs:
      correlation_id:
        description: 'Unique ID to correlate the dispatch with the run'
        required: true
        type: string

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Create HelloWorld.txt
        run: echo "Hello World!" > HelloWorld.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-artifact
          path: HelloWorld.txt
          retention-days: 1